syntax = "proto3";

package pdbd.v1;

import "pdbd/v1/common.proto";
import "pdbd/v1/tunnel.proto";

message EnvVar {
  string name = 1;
  string value = 2;
}

message PtySize {
  uint32 cols = 1;
  uint32 rows = 2;
}

message ExecRequest {
  repeated string argv = 1;
  repeated EnvVar env = 2;
  string cwd = 3;
  bool clear_env = 4;
}

message ShellRequest {
  repeated string argv = 1;
  repeated EnvVar env = 2;
  string cwd = 3;
  bool clear_env = 4;
  PtySize pty = 5;
}

message ResizeRequest {
  uint64 tunnel_id = 1;
  PtySize pty = 2;
}

message ResizeResponse {}

message Exited {
  int32 code = 1;
  int32 signal = 2;
}

message CommandEvent {
  oneof event {
    Tunnel opened = 1;
    Exited exited = 2;
    Error error = 3;
  }
}
